import asyncio


async def tcp_echo_client():
    """This function helps us to do the operations that we have choosen"""
    r,w = await asyncio.open_connection('127.0.0.1', 8898)
    opt = await r.read(100)
    t = opt.decode().strip()
    print(t)
    co = input()
    w.write(co.encode())
    if co == '1':
        view = await r.read(100)
        pulldata = view.decode().strip()
        nap = input(pulldata)
        w.write(nap.encode())
        view = await r.read(100)
        pulldata = view.decode().strip()
        prt = input(pulldata)
        w.write(prt.encode())
        view = await r.read(100)
        pulldata = view.decode().strip()
        pa = input(pulldata)
        w.write(pa.encode())
        viw = await r.read(100)
        pulldata = viw.decode().strip()
        print(pulldata)
        print("----Now you can Login----")
    if co != '1':
        viw = await r.read(100)
        pulldata = viw.decode().strip()
        prt = input(pulldata)
        w.write(prt.encode())
        viw = await r.read(100)
        pulldata = viw.decode()
        pas = input(pulldata)
        w.write(pas.encode())
        viw = await r.read(10000)
        pulldata = viw.decode().strip()
        print(pulldata)
        if pulldata == "You have logged in already\nAccess denied" or pulldata == "Invalid Userid or Password":
            exit()
        while True:
            c = input("Enter your choice : ")
            w.write(c.encode())
            if c == '1':
                viw = await r.read(100)
                pulldata = viw.decode().strip()
                prt = input(pulldata)
                w.write(prt.encode())
                viw = await r.read(100)
                pulldata = viw.decode().strip()
                print(pulldata)
            elif c == "2":
                viw = await r.read(50)
                pulldata = viw.decode().strip()
                fnonp = input(pulldata)
                w.write(fnonp.encode())
                viw = await r.read(50)
                pulldata = viw.decode().strip()
                prt = input(pulldata)
                w.write(prt.encode())
                viw = await r.read(50)
                pulldata = viw.decode().strip()
                iv = input(pulldata)
                w.write(iv.encode())
                viw = await r.read(100)
                pulldata = viw.decode().strip()
                print(pulldata)
            elif c == "3":
                viw = await r.read(100)
                pulldata = viw.decode().strip()
                fnonp = input(pulldata)
                w.write(fnonp.encode())
                viw = await r.read(100)
                pulldata = viw.decode().strip()
                prt = input(pulldata)
                w.write(prt.encode())
                viw = await r.read(100)
                pulldata = viw.decode().strip()
                print(pulldata)
            elif c == "4":
                viw = await r.read(100)
                pulldata = viw.decode().strip()
                print(pulldata)
                w.write("hi".encode())
                viw = await r.read(100)
                pull = viw.decode().strip()
                nan = list(pull.split(" "))
                w.write("hello".encode())
                viw = await r.read(20)
                view = viw.decode().strip()
                sze = list(view.split(" "))
                w.write("hello".encode())
                viw = await r.read(90)
                sr = viw.decode().strip()
                cre = list(sr.split("  "))
                w.write("hello".encode())
                viw = await r.read(90)
                sp = viw.decode().strip()
                po = list(sp.split("  "))
                w.write("hello".encode())
                for fl in range(len(nan)):
                    print(f"{nan[fl]}  {sze[fl]}   {cre[fl]}  {po[fl]}")
            elif c =='5':
                viw = await r.read(100)
                pulldata = viw.decode().strip()
                nonp = input(pulldata)
                w.write(nonp.encode())
                viw = await r.read(100)
                pulldata = viw.decode().strip()
                onh = input(pulldata)
                w.write(onh.encode())
                viw = await r.read(100)
                pulldata = viw.decode().strip()
                print(pulldata)
            elif c =="0":
                break
        viw = await r.read(100)
        pulldata = viw.decode().strip()
        print(pulldata)
    w.close()
asyncio.run(tcp_echo_client())
